In [1]:
import numpy as np

In [2]:
a = np.array((1,2,3))

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array((4,5,6))

In [5]:
b

array([4, 5, 6])

In [6]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [7]:
a = np.array([[1],[2],[3]])

In [9]:
a

array([[1],
       [2],
       [3]])

In [8]:
b = np.array([[4],[5],[6]])

In [10]:
b

array([[4],
       [5],
       [6]])

In [11]:
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])